apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notif-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notif-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notif-webhook
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notif-webhook
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notif-mock-provider
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notif-mock-provider
  minReplicas: 1
  # Dedicated mock-provider capacity: 2 on-demand + 4 spot nodes.
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
