apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api.yaml
  - api-hpa.yaml
  - webhook.yaml
  - webhook-hpa.yaml
  - worker.yaml
  - mock-provider.yaml
  - notif-config.yaml
  - servicemonitors.yaml
  - ingress-hosts.yaml
  - ../../grafana
