apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notif-api
  namespace: monitoring
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: notif-api
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notif-webhook
  namespace: monitoring
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: notif-webhook
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notif-webhook-processor
  namespace: monitoring
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: notif-webhook-processor
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notif-worker
  namespace: monitoring
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: notif-worker
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
