version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: notif-postgres
    environment:
      POSTGRES_USER: notif
      POSTGRES_PASSWORD: notif
      POSTGRES_DB: notif
    ports:
      - "5432:5432"
    volumes:
      - notif_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U notif -d notif"]
      interval: 5s
      timeout: 3s
      retries: 20

  localstack:
    image: localstack/localstack:3
    container_name: notif-localstack
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=ap-south-1
      - EDGE_PORT=4566
    ports:
      - "4566:4566"
    healthcheck:
      test: ["CMD", "bash", "-lc", "awslocal sqs list-queues >/dev/null 2>&1"]
      interval: 5s
      timeout: 3s
      retries: 30

volumes:
  notif_pgdata: