apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db-migrate-seed-job.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: notif-db-sql
    files:
      - sql/001_init.sql
      - sql/seed.sql
      - sql/phones.txt
