apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: notif-worker-sqs
spec:
  scaleTargetRef:
    name: notif-worker
  pollingInterval: 5
  cooldownPeriod: 90
  minReplicaCount: 2
  maxReplicaCount: 10
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: aws-sqs-auth
      metadata:
        queueURL: https://sqs.ap-south-1.amazonaws.com/000000000000/notif-send.fifo
        queueLength: "100"
        activationQueueLength: "5"
        awsRegion: ap-south-1
