apiVersion: apps/v1
kind: Deployment
metadata:
  name: notif-api
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notif-worker
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notif-webhook
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notif-mock-provider
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-pull
