apiVersion: apps/v1
kind: Deployment
metadata:
  name: notif-api
spec:
  template:
    spec:
      containers:
        - name: api
          image: notif-api:dev
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notif-webhook
spec:
  template:
    spec:
      containers:
        - name: webhook
          image: notif-webhook:dev
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notif-worker
spec:
  template:
    spec:
      containers:
        - name: worker
          image: notif-worker:dev
          imagePullPolicy: IfNotPresent
